feat: 회원가입 기능 개발
f-lab-edu/cozy pull request #11
Opened 2021-09-27 09:46 UTC by youngsuk-kim

## 작업 내용

## 체크 리스트
* [conventions](https://github.com/f-lab-edu/cozy/wiki/conventions)
- [x] 구글 자바 컨벤션 준수 여부
- [x] 객체지향 생활체조 원칙(3가지만) 준수 여부
- [x] 어노테이션에 주석 추가 여부  
- [x] 커밋 메시지 컨벤션 준수 여부
- [x] 테스트 코드 작성 여부

## 결과 (스크린샷 포함 가능)

## 참조자
@didrlgus, @youngsuk-kim, @f-lab-jd

2021-09-27 15:24 UTC, f-lab-jd commented on src/main/java/com/cozy/domain/user/service/UserService.java
> +        String encodePassword = BCrypt.hashpw(createUserDto.getPassword(), BCrypt.gensalt(10));
@youngsuk-kim 
1. 동사형 encode 보다는 `encoded` 가 더 적합해보입니다.
2. 매직넘버는 따로 상수로 빼는 것은 어떨까요? 
3. 암호화를 위해 BCrypt 를 사용하신 이유가 있을까요~?

2021-09-27 15:30 UTC, f-lab-jd commented on src/main/java/com/cozy/domain/user/service/UserService.java
> +        return userDao.createUser(dto);
@youngsuk-kim 
1. 이메일이 중복되는 경우에도 회원가입이 성공하는것이 스펙일까요?
2. loginId 길이가 25 초과하는 경우 어떤 현상이 발생할까요? 관련해서 테스트코드를 추가하시면서 예외상황에 대한 고려를 추가해주시면 좋을 것 같습니다.

2021-09-27 15:40 UTC, f-lab-jd commented on src/main/java/com/cozy/domain/user/dao/UserDaoJdbc.java
> +    public GetOneUserDto getOneUser(Long id) {
@youngsuk-kim 
DAO 에서 `getOneUser` 호출의 결과 ``GetOneUserDto` 를 리턴하도록 구현해주셨는데요.
`GetOneUserDto` 와 `User` 클래스는 어떤 차이가 있는건가요~?

2021-09-27 15:48 UTC, f-lab-jd commented on src/main/java/com/cozy/domain/user/service/UserService.java
> +        CreateUserDto dto = CreateUserDto.builder()
@youngsuk-kim 
https://github.com/f-lab-edu/cozy/pull/11/files#r716816073 와도 연관이 있는 내용인데요. 
Controller - Service -DAO 레이어에 전부 같은 dto 객체를 사용하도록 구현하셨는데,
dto 를 어느 레이어까지 적용하는게 적합할지 한번 고민해보셔도 좋을 것 같습니다. (cc. @didrlgus)

2021-09-27 15:55 UTC, f-lab-jd requested changes
@youngsuk-kim 
리뷰드린 내용 한번 참고부탁드리고, 
https://github.com/f-lab-edu/cozy/blob/main/src/main/resources/mapper/userMapper.xml
지난번에 작성해주신 위 mapper 소스코드에 대해서는 리뷰되지않았는데요.

쿼리와 컬럼명의 대/소문자 구분에 대해 일관성을 가지고 정확하게 관리가 되면 좋을 것 같습니다.
예를들면, sql 중 WHERE 절만 대문자이고, 컬럼중에는 ID 컬럼만 대문자로 관리가 되고 있습니다.

2021-09-28 13:11 UTC, didrlgus requested changes
@youngsuk-kim 
해당 PR에 controller에 대한 코드가 빠져있습니다.
앞으로 추가하실 예정이신건가요?

2021-09-28 13:21 UTC, didrlgus requested changes
@youngsuk-kim 
현재, 저희가 사전에 약속했던 디렉터리 구조를 따르지 않는 구조입니다.
(https://github.com/f-lab-edu/cozy/wiki/conventions#%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC-%EA%B5%AC%EC%A1%B0)
약속으로 정한 것이니, service 디렉토리를 바깥으로 빼내서 사전에 약속했던 컨벤션을 지키는 것이 옳다고 생각합니다.

2021-09-28 13:28 UTC, didrlgus requested changes
@youngsuk-kim 
저번 PR에서 @youngsuk-kim 께서 google convention invent를 +2로 두는 것이 가독성이 더 좋다고 하셔서 +2로 정했는데요. 해당 PR에서는 컨벤션이 하나도 지켜지지 않은 거 같습니다.
이 부분 수정 요청드립니다.

2021-09-28 13:53 UTC, didrlgus commented on src/main/java/com/cozy/domain/user/service/UserService.java
> +        CreateUserDto dto = CreateUserDto.builder()
@f-lab-jd @youngsuk-kim 
저는 개인적으로 Service 영역까지만 dto객체를 사용하고,
DAO 혹은 Repository 메서드 호출 시 파라미터로는 dto가 아닌 Entity(여기서는 User) 객체를 사용하는 것을 선호합니다.

2021-09-28 13:53 UTC, didrlgus commented on src/main/java/com/cozy/domain/user/dao/UserDaoJdbc.java
> +public class UserDaoJdbc implements UserDao {
@youngsuk-kim 
UserDao를 인터페이스로 정의한 이유와, UserDao 인터페이스의 구현 클래스 이름으로 UserDaoJdbc라는 이름을 사용한 이유가 궁금한데, 이유를 말씀해주실 수 있을까요?
추후에 UserDaoJpa와 같이 UserDao를 확장할 가능성이 있다고 판단해서 일까요?

2021-09-30 12:39 UTC, youngsuk-kim commented on src/main/java/com/cozy/domain/user/dao/UserDaoJdbc.java
> +public class UserDaoJdbc implements UserDao {
네 맞습니다! jpa를 사용할때를 생각해서 UserDao 인터페이스를 정의하고 구현체를 따로 만들었습니다

2021-10-04 14:54 UTC, f-lab-jd commented on src/main/java/com/cozy/constant/UserConstant.java
> +  public static final Integer LOG_ROUND = 10;
👍

2021-10-04 14:56 UTC, f-lab-jd commented on src/main/java/com/cozy/service/UserService.java
> +  @Transactional
@youngsuk-kim 
`@Transactional` 에 대한  설명이 있으면 더 좋을 것 같습니다.

2021-10-04 15:05 UTC, f-lab-jd commented on src/main/java/com/cozy/service/UserService.java
> +      throw new IllegalStateException("이미 존재하는 이메일 입니다");
@youngsuk-kim 
예외 관련해서는 저희가 토비의 스프링 책에서 배웠듯이 예외를  구체적으로 재정의해보아도 좋을 것 같습니다.

2021-10-04 15:06 UTC, f-lab-jd commented on src/test/java/com/cozy/domain/user/UserMapperTest.java
> +        .hashpw("1234", BCrypt.gensalt(LOG_ROUND));
@youngsuk-kim 
개행을 한 이유가 혹시 code-style 때문일까요~?

2021-10-04 15:07 UTC, f-lab-jd approved these changes
@youngsuk-kim 님 고생하셨습니다! 
리뷰드린 부분은 다른 feature 를 개발하며 차차 수정해도 좋을 것 같습니다.
(cc. @didrlgus)

2021-10-06 01:02 UTC, merged