build: mysql mybatis 설정 추가
f-lab-edu/cozy pull request #4
Opened 2021-09-20 04:30 UTC by youngsuk-kim

## 작업 내용
- mybatis 연동 의존성 추가
- mysql 연동 의존성 추가
- mysql 연동 설정 코드 추가
- mysql 연동 테스트 코드 추가
- 로컬 디비 설정을 위한 mysql docker compose 파일 추가

## 체크 리스트
* [conventions](https://github.com/f-lab-edu/cozy/wiki/conventions)
- [ O] 구글 자바 컨벤션 준수 여부
- [ O] 객체지향 생활체조 원칙(3가지만) 준수 여부
- [ O] 어노테이션에 주석 추가 여부  
- [ O] 커밋 메시지 컨벤션 준수 여부
- [ O] 테스트 코드 작성 여부

## 결과 (스크린샷 포함 가능)

## 참조자
@didrlgus, @youngsuk-kim, @f-lab-jd

2021-09-20 07:42 UTC, didrlgus commented on mysql-docker-compose.yml
> +    image: mysql:5.7
@youngsuk-kim 
mysql 버전을 5.7로 선택한 특별한 이유가 혹시 있으실까요?

2021-09-20 07:42 UTC, didrlgus commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
@youngsuk-kim 
테스트 용도로 사용할 디비라면, 혹시 임베디드 디비 (h2와 같은)를 사용하는 것에 대해서는 어떻게 생각하시나요??

2021-09-20 20:57 UTC, youngsuk-kim commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
> @youngsuk-kim
> 테스트 용도로 사용할 디비라면, 혹시 임베디드 디비 (h2와 같은)를 사용하는 것에 대해서는 어떻게 생각하시나요??

음 로컬 개발 디비를 프로덕션 환경에서 사용하는 디비와 동일하게 하지 않으면 문제가 생기지 않을까요?
왜 h2를 사용해야 하는지 궁금하네요!

2021-09-21 03:51 UTC, didrlgus commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
@youngsuk-kim 
꼭 h2를 사용해야된다 라는건 아니였구여.
h2와 같은 임베디드 디비를 사용하면, 애플리케이션 외부에 따로 디비 세팅을 하지 않고도 테스트를 진행할 수 있다는 장점이 있어서 제안 드려보았습니다.
말씀주신대로, 테스트 디비와 프로덕션 디비가 다르면 문제가 될 우려가 있기는 하지만, H2 연동 시 특정 벤더(Mysql, oracle...)의 구문과 호환되도록 설정해주는 옵션도 존재하긴 합니다.

2021-09-22 03:53 UTC, didrlgus commented on src/test/java/com/cozy/domain/user/UserMapperTest.java
> +import com.cozy.domain.user.mapper.UserMapper;
@youngsuk-kim 

현재, CreateUserDto와  UserMapper에 대한 코드가 빠져있습니다. 의도하신걸까요?

2021-09-22 04:37 UTC, didrlgus commented on src/main/java/com/cozy/domain/user/User.java
> +}
@youngsuk-kim
저희 indent를 통일하는게 좋을 것 같습니다.
구글 자바 컨벤션에서  정의되있는 바로는 @youngsuk-kim 님께서 작성하신대로 +2가 맞습니다.
다만, 제가 별다른 상의도 없이 indent를 4로 주고 코딩을 하고 있었는데요. 이는 구글 자바 컨벤션에 어긋나는 것이지만, 그럼에도 불구하고 제 개인적으로는 +4가 더 코드의 가독성이 좋다고 생각했습니다.
@youngsuk-kim 께서 꼭 구글 자바 컨벤션에 맞게 +2를 지키고 싶다고 하신다면, 제가 @youngsuk-kim 의견에 맞추도록 하겠습니다. 
그렇지 않고, +2나 +4나 상관이 없으시거나 +4에 동의하신다면 +4로 가면 좋을 것 같습니다.
@youngsuk-kim 님의 의견을 제시해 주시면 감사하겠습니다.

2021-09-23 00:04 UTC, youngsuk-kim commented on src/main/java/com/cozy/domain/user/User.java
> +}
@didrlgus 저는 컨벤션에 맞게 +2로 가는게 가독성에 좋다고 생각합니다!

2021-09-23 00:06 UTC, youngsuk-kim commented on src/test/java/com/cozy/domain/user/UserMapperTest.java
> +import com.cozy.domain.user.mapper.UserMapper;
@didrlgus 아뇨 빼먹고 커밋을 했네요 추가하도록 하겠습니다!

2021-09-23 03:15 UTC, f-lab-jd commented on mysql-docker-compose.yml
> +# 로컬 개발 환경 설정을 위한 MySQL docker compose 파일
@youngsuk-kim 
`로컬 DB 환경`을 위해 도커 컴포즈를 사용한것이죠~? 
도커 컴포즈는 여러개 컨테이너를 정의하고 공유하는 용도인데, mysql 만을 위해 사용하는 이유가 있으실까요?

2021-09-23 03:16 UTC, f-lab-jd commented on src/main/java/com/cozy/domain/user/User.java
> +@Getter
@youngsuk-kim 
아직 사용되는 부분이 없어서 정확히 파악하지는 못했지만, 
immutable 이 목적이라면 lombok 에서 제공하는 `@Value` 어노테이션으로 대체할 수도 있을까요?

2021-09-23 03:30 UTC, f-lab-jd commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
[h2](https://www.h2database.com/html/main.html) 의 가장 큰 장점은 인메모리 디비이기때문에 빠르다라는 점입니다. 
이러한 면에서 프로젝트의 규모가 커질수록, 테스트코드가 많아질수록 h2 의 장점은 더 빛을 발합니다. (진짜 가볍습니다..)
기현님께서 말씀하신것처럼 다양한 벤더를 제공해서, mysql 모드로 쉽게 실행도 가능하구요. 그치만 영석님께서 말씀하신것처럼 테스트 환경과 프로덕션 환경이 다른 DB 를 사용한다는 점에서, MYSQL 모드를 사용한다고해도 리스크와 불안감이 생길 수도 있습니다.

개인적으로는 로컬 개발환경 / 테스트환경을 위해 아래 선택지로 고민 할 수 있을 것 같은데요. 
1. 두 환경 모두 docker 를 사용하느냐 
2. 로컬 개발환경은 docker, 테스트환경은 h2 를 사용하느냐
3. 두 환경 모두 개발환경과 동일한 DB 를 사용하느냐  (naver cloud 를 통해 구축해야겠죠) 
4. 로컬 개발환경은 개발DB, 테스트환경은 h2 를 사용하느냐

각각의 장단점을 잘 고려하여 두분의 상의를 통해 판단해주시면 좋을 것 같습니다. @youngsuk-kim @didrlgus

2021-09-23 03:33 UTC, f-lab-jd commented on src/main/resources/schema.sql
> +    is_deleted   BOOLEAN      not null DEFAULT false,
@youngsuk-kim 
아직 테이블을 정확하게 설계하신것은 아니실테지만, 비밀번호나 이메일을 변경하는 케이스에는 수정일시 컬럼도 필요하지 않을까요?

2021-09-23 03:33 UTC, f-lab-jd commented on src/test/java/com/cozy/MySQLConnectionTest.java
> +   * 필요한 의존 객체의 타입에 해당하는 빈을 찾아 주입한다.
👍

2021-09-23 03:38 UTC, f-lab-jd commented on src/test/java/com/cozy/domain/user/UserMapperTest.java
> +    userMapper.createUser(user);
@youngsuk-kim  
생성을하고(`createUser` 메소드를 수행하고) 이상이 없으면 (`exception` 이 발생하지 않으면) 기대한대로 user 가 생성되었다고 생각해도 될까요? `given-when-then` 패턴에 맞게 테스트코드를 작성하시면 더 신뢰있고 가독성좋은 테스트코드가 될 것 같습니다.

2021-09-23 03:39 UTC, f-lab-jd requested changes
테스트코드 누락된 코드만 추가해주시면 좋을 것 같습니다.

2021-09-23 07:23 UTC, youngsuk-kim commented on mysql-docker-compose.yml
> +# 로컬 개발 환경 설정을 위한 MySQL docker compose 파일
@f-lab-jd 도커 이미지를 실행하는데 필요한 명령어를 작성하는것이 번거로워서 도커 컴포즈를 사용했습니다!

2021-09-23 07:31 UTC, youngsuk-kim commented on src/main/java/com/cozy/domain/user/User.java
> +@Getter
@f-lab-jd '@Value' 는 고려하지 못했습니다. 사용해보도록 하겠습니다!

2021-09-23 11:53 UTC, f-lab-jd approved these changes
👍 👍

2021-09-23 12:30 UTC, didrlgus commented on src/main/java/com/cozy/domain/user/User.java
> +}
@youngsuk-kim 넵, 앞으로 +2로 통일 시키도록 하겠습니다.

2021-09-23 14:14 UTC, didrlgus commented on mysql-docker-compose.yml
> +# 로컬 개발 환경 설정을 위한 MySQL docker compose 파일
@f-lab-jd
말씀해주신대로, 단일 컨테이너를 띄우는게 목적이라면 아래와 같이 Dockerfile로 대체 가능할 것 같습니다.
``` Dockerfile
FROM mysql:5.7
ENV MYSQL_ROOT_PASSWORD 1234
ENV MYSQL_DATABASE cozy
ENV MYSQL_USER cozy
ENV MYSQL_PASSWORD 1234
EXPOSE 3306
CMD ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
```
다만, 추후에 다른 컨테이너를 또 띄우게 될 상황도 있을 수 있을 것 같아서 개인적으로는, docker compose 환경을 미리 갖추어 두고 사용해도 무방할 것 같다는 생각입니다.
또한, Dockerfile은 해당 파일에 대한 build 명령어로 이미지 생성 후, run 명령어로 이미지를 실행하는 반면, docker compose는 docker compose 명령어만 치면 build -> run을 한꺼번에 수행하기 때문에 사용하는 입장에서도 더 편리하다는 생각이 듭니다.
결론적으로, docker compose 환경을 추가적으로 갖춰야 한다는 단점 외에 단일 컨테이너를 docker compose로 정의할 경우 치명적인 문제가 있는게 아니라면 docker compose로 작성하는 것도 괜찮다고 생각합니다.

2021-09-23 14:37 UTC, didrlgus commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
@f-lab-jd 님께서 제안 주신 선택지 중 3번에 대해 정확히 이해하지 못했는데요.
두 환경(로컬 개발환경과 테스트환경) 모두 개발환경과 동일한 DB를 사용한다라고 볼 수 있을거 같은데, 로컬 개발환경 말고 개발환경이라는 또 다른 환경이 존재하는 것일까요?? 이부분이 잘 이해가 안되는 것 같습니다.

2021-09-23 15:12 UTC, f-lab-jd commented on src/main/resources/application.yml
> +    driver-class-name: com.mysql.cj.jdbc.Driver
@didrlgus 
아래 세가지 환경이 존재한다는 가정하에 위에 3,4번 옵션을 말씀드렸습니다.
* 로컬(local) 환경
* 개발(dev) 환경 
* 운영(production) 환경 

개발(dev) 환경은 개발자들이 만든 코드를 통합해서 서버 환경에서 테스트하기 위한 용도의 환경인데요. 
개발 환경에서의 서비스를 위해 별도의 개발 DB 를 구축하고, 이를 로컬에서 참조한다라는 의미였습니다. 
`배포 환경`  이라는 키워드로 관련해서 한번 찾아보시고, 어떠한 배포 환경을 가져갈지 먼저 고민해도 좋을 것 같네요.

2021-09-23 15:50 UTC, f-lab-jd commented on mysql-docker-compose.yml
> +# 로컬 개발 환경 설정을 위한 MySQL docker compose 파일
@youngsuk-kim  @didrlgus 
컨테이너 build & run 을 위해 간결한 문법을 제공한다는 점 이외에 docker-compose 를 사용하는 이유가 있으실까요? 
두분께서 Docker 에 대한 이해도가 어느정도이신지 정확히 모르지만, 컨테이너기술에 대한 이해가 먼저 선행되어야 한다고 생각합니다.
왜 Docker 를 사용하는지, 왜 docker-compose 인지, 다른 대안은 무엇이 있는지 등 docker 와 docker-compose 를 사용하는 이유에 대해 고민해보시고 더 구체적으로 정리가 되면 좋을것 같습니다. 더구나 학습이 목적인 프로젝트인만큼 사용하는 기술 하나하나 `왜 사용하는지` 생각해보는 습관을 들이시면 좋을 것 같습니다. 그리고 추 후 mysql 이 아닌 다른 컨테이너를 띄우는 목적이 분명하다면, docker-compose 의 파일 네이밍 룰에 맞추어서 `docker-compose.yml` 로 네이밍하는게 좋을 것 같습니다.

2021-09-23 16:05 UTC, f-lab-jd commented
@youngsuk-kim @didrlgus 
해야 할 작업들을 issue 로 먼저 등록 후 진행해주시면 더 좋을 것 같습니다. 
그리고 혹시 머지 조건에 `Unresolved conversations` 은 빼는것은 어떨까요? ㅎㅎ 
저희 모두가 full-time 으로 cozy 프로젝트를 진행하는게 아닌데, discussion 까지 해결되기 기다리는것은 너무 타이트해서, 진행 속도가 더뎌 질 수도 있을것 같습니다. Approve 는 슬랙에서 이야기 나누었던것처럼 당분간은 현재 제약이 좋을것같습니다. 
아니면 리뷰시 발생하는 커뮤니케이션으로 인해 개발 속도가 더뎌진다면, [뱅셀에서 적용하고 있는 룰](https://blog.banksalad.com/tech/banksalad-code-review-culture/#%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98-%EB%B9%84%EC%9A%A9%EC%9D%84-%EC%A4%84%EC%9D%B4%EA%B8%B0-%EC%9C%84%ED%95%9C-pn-%EB%A3%B0) 을 적용도 고려해보아도 좋을 것 같습니다.

2021-09-24 01:07 UTC, merged

2021-09-24 02:33 UTC, didrlgus commented on mysql-docker-compose.yml
> +# 로컬 개발 환경 설정을 위한 MySQL docker compose 파일
@f-lab-jd 
말씀주신대로, 컨테이너에 대한 이해가 선행돼야 할 것 같습니다.
추후에, 도커에 대한 구체적인 정리를 블로그로 포스팅하거나 이슈로 정리해보겠습니다.